version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm ci
  build:
    commands:
      - echo Building...
      - npm run build --if-present
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - server.js
    - package.json
    - node_modules/**/*
